name: Publish

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Perform a dry run (do not publish)'
        required: false
        type: boolean
        default: false
  push:
    tags:
      - 'v*.*.*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Verify package can be published
        run: cargo publish --dry-run

      - name: Publish to crates.io
        if: ${{ !inputs.dry-run }}
        run: cargo publish --token ${{ secrets.CARGO_TOKEN }}
